import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import Ai_assistant from "@/components/Ai_assistant";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CASAHOST",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased font-sans`}
    >
      <body className="min-h-full flex flex-col dark:bg-slate-950">
        <Header />
        <div className="grow min-h-full my-10 pt-16">{children}</div>
        <Footer />

        <Popover>
          <PopoverTrigger
            className="fixed bottom-6 right-6 z-50 cursor-pointer rounded-full bg-linear-to-r from-amber-400 to-orange-500 px-5 py-3 text-sm font-semibold text-slate-950 shadow-lg shadow-amber-500/25 transition-transform hover:scale-105"
            type="button"
          >
            AI CHAT
          </PopoverTrigger>

          <PopoverContent
            side="top"
            align="end"
            sideOffset={12}
            className="w-[90vw] max-w-sm rounded-[15px] border border-gray-200 bg-white p-0 shadow-xl dark:border-white/10 dark:bg-[#111827] sm:max-w-md md:max-w-2xl lg:max-w-3xl"
          >
            <Ai_assistant />
          </PopoverContent>
        </Popover>
      </body>
      
    </html>
  );
}
